### ISSUE TITLE
Dashboard revamp tracking ticket

### ISSUE THREAD

**Issue by rmars** [BuoyantIO/linkerd#183]
Revamp the linkerd dashboard page.
This ticket documents the tasks to get the new dashboard up and running (rough/beta version).
Getting ready to release a v1 is tracked in #275 

The plan:
* [x] #184 Set up a skeleton endpoint for dashboard v2.  This will include:
  + handler (scala)
  + blank html page
* [x] #184 Set up base js and css files. This will include:
  + an update function to poll for metrics
  + js app initialization/entrypoint
  + set up css files for later reference
* Data plumbing work:
  * [x] #195 Write a metrics js module to handle getting the data we need
  * [x] #215 Write a query util for clientside metrics gathering
  * [x] #224
* Write js (sub)components for the new dashboard.
    * [x] #193 a banner component that displays an overview
    * [x] graph component that displays realtime results
      * [x] #186 / #227 combined router graph
      * [x] #241 per client graph that displays latencies
    * [x] #185 a (per client) table / lengend displaying latencies
    * [x] #187 a summary component containing prominent metrics (requests, connections, success/fail rate)
    * [x] #220 write a server module (contains server summary)
    * [x] #231 write a client module (contains table and graphs, and also a summary)
* Styling - make the dashboard look like the mocks.
  * [x] #233 set up grid layout
  * [x] #242 colorize the dashboard: the colors in the overview chart must match the client colors
  * [x] #250 apply stylings from the mocks to the dashboard
* Fix bugs
  * [x] add ``failure rate || null`` to prevent NaN%s in the success rates (related: #258)

**Questions**
* What js frameworks do we want to use? backbone? react?
  + let's try to avoid dependencies as much as possible
* What do we want to use for the graphs? d3? smoothie?
  + we decided to use smoothie for now to make use of the existing UpdateableChart, and revisit in the future
* Do we want this page responsive design? The current spec is very specific pixel-wise.
  + Filed #234 

Comments/discussion on plans/technologies welcome.

**Comment by rmars** [comment]
Latest design specs: 
[color_guide.pdf](https://github.com/BuoyantIO/linkerd/files/189807/color_guide.pdf)
[default_view_grid.pdf](https://github.com/BuoyantIO/linkerd/files/189808/default_view_grid.pdf)
[default_view_spec_typography.pdf](https://github.com/BuoyantIO/linkerd/files/189809/default_view_spec_typography.pdf)
[router_detail_sizing_spec.pdf](https://github.com/BuoyantIO/linkerd/files/189811/router_detail_sizing_spec.pdf)
[router_detail_styles.pdf](https://github.com/BuoyantIO/linkerd/files/189812/router_detail_styles.pdf)
[router_detail_typography_spec.pdf](https://github.com/BuoyantIO/linkerd/files/189810/router_detail_typography_spec.pdf)

**Comment by rmars** [comment]
The initial dashboard (rough version) is in master, so I am closing this.
Work towards a general release will be tracked in #275
