### ISSUE TITLE
Dashboard v1 tracking ticket

### ISSUE THREAD

**Issue by rmars** [BuoyantIO/linkerd#275]
Continued from #183, but making a new ticket since we've now completed the base dashboard, and the old one is getting cluttered.

Things that need to be done to 'release' this:
* [x] #347 add navbar to the new dashboard

Things that maybe don't have to be in release V1, but should be eventually addressed:
* [x] #222 Ensure the dashboard looks good in !chrome (was: Fix dashboard in safari)
* [x] #265 Fix request URI too long errors in dashboard data requests
* [x] #264 use correct fonts in the new dashboard
* [x] decide what we're going to do about Success/Failure rates (going to call this ~done with #436)
  + Should we remove failure rates entirely and just have failure counts?
  + Should success rate just be one colour or should it change based on how good the SR is?
  + If we keep failure rates, that code needs to be put into utils.js
* [x] #234 Responsiveness in the dashboard
* [x] #251 clean up router_clients.js
* [ ] #238 clean up Query module code / repetition
* [x] #381 make a lot of the repeated metrics modules handlebars templates
* [x] #304 go over the design specs and make sure all the details are implemented
* [x] #472 Enable one router per page / Be able to sort/collapse clients/servers under a router
* [x] Oliver prefers client names to be prefixed with "/" (fixed in #347)
* [ ] Tests! A build system too?

When we have verified we would like to get rid of the old dashboard:
* Cleanup tickets, THEN, finally: delete the old dashboard and clean up the code that depended on it. 
    * [x] #198 Delete the old dashboard and remove associated TODOS

**Comment by rmars** [comment]
![router_detail](https://cloud.githubusercontent.com/assets/549258/14473547/8a14a562-00ad-11e6-8a41-039d245b72bb.png)
[color_guide.pdf](https://github.com/BuoyantIO/linkerd/files/215822/color_guide.pdf)
[default_view_grid.pdf](https://github.com/BuoyantIO/linkerd/files/215823/default_view_grid.pdf)
[default_view_spec_typography.pdf](https://github.com/BuoyantIO/linkerd/files/215821/default_view_spec_typography.pdf)
[router_detail_sizing_spec.pdf](https://github.com/BuoyantIO/linkerd/files/215826/router_detail_sizing_spec.pdf)
[router_detail_styles.pdf](https://github.com/BuoyantIO/linkerd/files/215824/router_detail_styles.pdf)
[router_detail_typography_spec.pdf](https://github.com/BuoyantIO/linkerd/files/215825/router_detail_typography_spec.pdf)

**Comment by rmars** [comment]
I'm going to close this out, as we no longer need it to keep track of a long list of dashboard TODOs :)
